INSERT INTO brands (name, plan, amount, amplitude_emails) VALUES
  ('Bonn ton', 'Growth', 1500, '{"abhishekprasad@bonntonn.com"}'::text[]),
  ('Sri Sangeetha’s', 'Pro', 2000, '{"sangeethashotels@gmail.com"}'::text[]),
  ('Radhika’s South Indian', 'Lite', 500, '{"erp.radhikas@gmail.com"}'::text[]),
  ('Subway baroda', 'Growth', 5900, '{"shahsmitp@gmail.com"}'::text[]),
  ('Gud mishri', 'Growth', 1000, '{"krunalakbari233@gmail.com"}'::text[]),
  ('Friends and Fries cafe', 'Growth', 1000, '{"lalanirajiv@gmail.com"}'::text[]),
  ('Kulcha Theka', 'Pro', 2000, '{"ruprofoods@gmail.com"}'::text[]),
  ('Student Housing', 'Growth', 10000, '{}'::text[]),
  ('Fountain Hospitality', 'Growth', 1500, '{"marketing@fountainhospitality.com"}'::text[]),
  ('My Baby', 'Growth', 1200, '{}'::text[]),
  ('Adige Dosa House', 'Pro', 2000, '{"adigedosahouse@gmail.com"}'::text[]),
  ('Door No 3 / Humble Krumble', 'Growth', 1500, '{"karmnaresh@gmail.com"}'::text[]),
  ('Roadster Hospitality', 'Growth', 1500, '{"ira@roadsterhospitality.com"}'::text[]),
  ('SVN Hotels', 'Growth', 1500, '{"yaswanth.gudisa@svnlakepalace.in"}'::text[]),
  ('Chianti', 'Lite', 1000, '{"kaverisastry@gratefulbread.in"}'::text[]),
  ('Vanakkam punjab', 'Pro', 1125, '{"vanakkampunjaabtirupur@gmail.com"}'::text[]),
  ('Migration Overseas', 'Growth', 5900, '{"shahsmitp@gmail.com"}'::text[]),
  ('Chai Mitra', 'Growth', 12000, '{}'::text[]),
  ('Zelebrae', 'Growth', 1500, '{"zelebraepastries@gmail.com"}'::text[]),
  ('Sri Annapurna Foods', 'Pro', 1500, '{"umang.jj@sriannapurna.in"}'::text[]),
  ('Gurjot', 'Growth', 499, '{}'::text[]),
  ('Alice in Gelato land', 'Pro', 2000, '{"aasim.merchant@gmail.com"}'::text[]),
  ('Stellar Clinic', 'Growth', 5900, '{"shahsmitp@gmail.com"}'::text[]),
  ('One elevan egg', 'Growth', 1000, '{"mdrustmali@gmail.com"}'::text[]),
  ('Beyond Burg', 'Pro', 2000, '{"beyondburgmarketing@gmail.com"}'::text[]),
  ('RR Durbar', 'Pro', 2000, '{"spperavali@rrdurbar.com","ramana.peravali@rrdurbar.com"}'::text[]);
